name: algorithmAutoSorter
on:
  push:
    branches: [ main ]

jobs:
  uploadToNotion:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependency
      run: pip install -r requirements.txt

    - name: sort-and-upload-request
      env:
        REQUEST_URL: ${{ secrets.REQUEST_URL}}
        COMMIT_MSG: ${{github.event.head_commit.message}}
        COMMIT_PATTERN: ${{vars.COMMIT_PATTERN}}
      run: python requestNotionUpload.py